### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by marcelklehr** [magpie-ea/magpie-base#18]
hey!

I just wanted to get some feedback on the API so far. (cc @x-ji @DiGyt)

1. The magic magpie property is currently named `$exp`, but I'm pondering renaming it, e.g. `$experiment` or even `$magpie` to make it obvious what this is.
2. The trials mechanism allows specifying trial data once via the trials prop of the Experiment component and then accessing single data points via e.g.`$exp.trial.color`. To make it more clear that this is not an array, I'm considering renaming this to `$exp.currentTrial.color`. That would make it more verbose, however.

What do you think?

**Comment by michael-franke** [comment]
I wouldn’t mind the verbosity.

I’d vote for `$magpie.currentTrial.color`.

**Comment by DiGyt** [comment]
completely agree with Michael. $magpie also looks like the clearest option to me. And for point two, I also think its better if you specify something like .curTrial or .currentTrial there. Don't think that this would be too long...

**Comment by marcelklehr** [comment]
Alrighty, thanks for your input! :)

**Comment by x-ji** [comment]
Makes sense. Being explicit is always good :)
