### ISSUE TITLE
Implement trial views

### ISSUE THREAD

**Issue by marcelklehr** [magpie-ea/magpie-base#2]
## Trial views
            Forced choice (2 alternatives)
            Sentence choice
            Image selection
            Textbox Input task
            Slider rating
            Dropdown choice
            Rating scale
            Key press

**Comment by marcelklehr** [comment]
@michael-franke Do you think it would be useful / desirable to support views that look like this? I.e. with multiple responses per view. 

![image](https://user-images.githubusercontent.com/986878/87450887-6b8daa00-c5ff-11ea-8b25-bf55ee75ced8.png)

**Comment by michael-franke** [comment]
This could be very useful, especially if generalized to different types of questions. Currently the postSurvey view has a bunch of these lumped into one view. It’s very inconvenient presently to customize this, as it entails adding HTML and JS for response handling, with the usual book-keeping entailed. So, if a generalzation of this could cover a more flexible post-survey view, that would already be very helpful.
