### ISSUE TITLE
Variables for syncing up over socket [Question]

### ISSUE THREAD

**Issue by DiGyt** [magpie-ea/magpie-base#22]
Got another question (probably for @x-ji ):

I'm currently fixing the last stuff for my interactive experiment. One part is to make sure the two socket partners sync up correctly. For that I need 2 networked variables on which I can base my random trial and condition assignment.

One variable needs to differ between interactive partners, such that I can put partner A in condition 1 and partner B in condition 2.

The other variable needs to remain constant for both partners, but needs to differ for each new instantiation of the experiment, such that I can feed each new pair with new trial data (while the trial data is consistent for the pair).

 After testing it out I think that the first variable I'm looking for is `socket.variant` (differing within a pair) and the second variable I'm looking for is `socket.chain` (differing between experiment instances). However I believe that `socket.chain` actually only increases for simultaneous instances of the experiment, and not for subsequent instances of the experiment (in the case óf pair 2 starting after pair 1 has finished).
 
 Can you maybe quickly confirm/falsify my assumptions?
 
 And if the last one is true can you maybe tell me what else I could use, or how I can introduce additional variables to socket which track the number of instantiations of an experiment?
 
 Sorry again for my illiteracy when it comes to socket :D
 
 PS.: I think it would be nice to have this in somewhere in the documentation!

Edit: Just noted that you can't seed Math.random() in JavaScript, so I'm not sure anymore whether it will be faster to seed based upon some socket variables, or whether I just should assign/generate the trials with Partner A, and them send them to Partner B via socket. What do you think?

**Comment by x-ji** [comment]
> or whether I just should assign/generate the trials with Partner A, and them send them to Partner B via socket.

Yep, this is what we've been doing in previous interactive experiment examples such as the color reference game: https://github.com/magpie-ea/magpie-color-reference

**Comment by x-ji** [comment]
Thanks for raising this point. I think the documentation regarding what each of `variant`, `chain`, `realization` means is displayed when one creates a new experiment: https://magpie-demo.herokuapp.com/experiments/new Though maybe we can also add better documentation/example regarding how to use them in the frontend? WDYT @marcelklehr

**Comment by x-ji** [comment]
> However I believe that socket.chain actually only increases for simultaneous instances of the experiment, and not for subsequent instances of the experiment (in the case óf pair 2 starting after pair 1 has finished).

I'm not sure I get what you mean. I think supposedly this mechanism should work like this, with e.g. 2 variants, 10 chains, 1 realizations specified in total:

- Participant 1: <1, 1, 1>
- Participant 2: <2, 1, 1>
- Participant 3: <1, 2, 1>
- Participant 4: <2, 2, 1>

etc. etc....

It shouldn't matter whether the experiments from participants 1 and 2 are still in progress or are already finished, the third participant should always be assigned <1, 2, 1> and the fourth <2, 2, 1> usw. Unless the participants 1 and 2 quit the experiment before submitting, then the slots <1, 1, 1> and <2, 1, 1> will be reset and be free for the participants joining next-in-line to take.

If this is now how the actual behavior is, I'll take a look into it.

**Comment by DiGyt** [comment]
Ahhhh, thanks @x-ji  !

> It shouldn't matter whether the experiments from participants 1 and 2 are still in progress or are already finished

Yes, that's exactly what I was hoping for. That effectively gives me everything I need. Thank you so much for clearing that up :)

> Could you describe the exact steps to reproduce the behavior you mentioned?

Yeah, I experienced it exactly in the way you describe it here. Just wasn't sure about it since I did it during debugging with `npm run serve`. So nothing to worry here...

> Yep, this is what we've been doing in previous interactive experiment examples

That's probably the more elegant way, indeed. I've already adapted the "parallel solution" based on a custom RNG seeded via `chain` and `variant` but I'll try to adapt the networking solution instead.

Thank you so much @x-ji for all the info (and also for the quick reply)! :grin: 

If you want, you can close this Issue again...

**Comment by x-ji** [comment]
No worries. Glad to help :)
