### ISSUE TITLE
Bugs in v0.3.0

### ISSUE THREAD

**Issue by DiGyt** [magpie-ea/magpie-base#23]
Sorry for being annoying, but I've found a few bugs with the new version:

Problem 1 - `magpie.addTrialData` seems to not  be defined:

After reinstalling the new magpie, generating a new experiment via `magpie new experiment` installing and serving it, I get errors when clicking on a button that's linked to the addTrialData function:
 
```
[Vue warn]: Error in v-on handler: "TypeError: _vm.$magpie.addTrialData is not a function"

found in

---> <ForcedChoiceInput> at node_modules/magpie-base/src/components/inputs/ForcedChoiceInput.vue
...
```
and
```
TypeError: _vm.$magpie.addTrialData is not a function
```

`addResults` on the other hand still works.

Problem 2 - When trying to log the chat message data, as @marcelklehr proposed in Issue #21 , the fact that the Chat screen is now also a template seems to create a bug: After being done chatting and clicking the button for the next screen, the heading of the next screen is rendered, but instead of the correct next screen content (e.g. a slider window), the chat component shows again, with full functionality. If you click the button again, you skip directly further, ignoring the component that would have come after the chat screen.

You should be able to reproduce this bug with the following MWE:
```html
      <ConnectInteractive />

      <Screen :title="'Chat'">
        <template #0="{responses}">
          <Chat :messages.sync="responses.messages"></Chat>
          <button @click=
                      "
                      $magpie.addResult({question:'messages', answer: responses.messages});
                      $magpie.nextScreen();">
            Leave Chat</button>
        </template>
      </Screen>

      <Screen :title="'Posttest'">
        <template #0="{responses}">
          <SliderInput
              left="Very Unfair"
              right="Very Fair"
              initial="50"
              :response.sync="responses.slider"
          />
          <button @click=
                      "
                      $magpie.addResult({question: 'posttest', answer:  responses.slider});
                      $magpie.nextScreen();">
            Continue</button>
        </template>
      </Screen>
```

Can you tell me what's the problem here and whether I'm doing something wrong?

**Comment by marcelklehr** [comment]
> Sorry for being annoying

Feedback is always valuable, never an annoyance :)
It appears the project template was still installing the old version of magpie :see_no_evil: This should be fixed now. As this may also have affected your second problem, can you try this again as well?

**Comment by marcelklehr** [comment]
Did you try this again? Does it work with the latest version?

**Comment by DiGyt** [comment]
Hey @marcelklehr I've already diverged too much with my own version of the experiment that it will take quite some time to update it. So, maybe I'll give it a try in the following weeks, but I can't tell you for sure when... Sorry for that :/

Anyhow, I'm sure that you managed to solve the issue and checked if it worked, so if you want to close the issue, please go ahead :)
