### ISSUE TITLE
Additions to the Chat component

### ISSUE THREAD

**Issue by DiGyt** [magpie-ea/magpie-base#24]
Hey everyone, this is probably for you @marcelklehr 

During the work on our interactive chat experiment and from the discussion I had with @michael-franke , I though that several things should be added to the chat component:

- [x] As of now, when logging chat messages, we can log author and the content of the chat message. However, Michael emphasized that it would be probably worth to also broadcast the current time each time a message is sent. This will later allow the experimenter to better untangle confusing threads as they occur when the chat partners send messages at almost the same time.
- [x] Speaking of that, logging the chat messages as given in 0.3.0 via simply adding `:messages.sync="responses.messages"` and `$magpie.addTrialData(responses);` will result in the .csv log of the chat messages only reads `[object object]` (as objects aren't serialized in the results). Of course we can extract the content of these objects before `addTrialData` however, it would be better if `:messages.sync="responses.messages"` and `$magpie.addTrialData(responses);` would give you some clear data already, (My guess is that it would be easiest to add some form of serialization of objects, such that `addTrialData` returns a field that could look similar to this): question: `chat messages`, answer: `[{author:Me, content:"Hi", time:2021-03-03-15-23-23}, {author:Partner, content:"What's up", time:2021-03-03-15-23-24}, ...]`. 
Michael also suggested having this data in a format that can be easily converted to a structured table with columns [author, message, time] and a row for each message.
- [x] The biggest practical challenge to using the chat component for me was not knowing whether your partner is there or not. You could e.g. throw some messages into the ether but your partner would never receive them because she/he was still lingering in the previous screen while you were in the chat screen already (the same problem occurs when one person leaves the chat unexpectedly). This becomes especially problematic, when you want to have multiple subsequent Chat screens in one experiment.
_
I think a good way to solve this is to have a status indicator somewhere that tells you stuff like `Your partner has not yet entered the chat`, `Your partner is active` or `Your partner has left the chat`. Having this status indicator in the chat component makes it instantly more comfortable to handle, so I would really advocate for including it as a standard.
_
I made a very crude implementation of this in my [experimental code](https://github.com/DiGyt/language-pragmatics/blob/318813f0e9a3a62743427611c39aa9c3f578b655/src/components/AltChat.vue) (Experiment link: [https://sad-bhabha-077723.netlify.app](https://sad-bhabha-077723.netlify.app)). I know my code is really ugly, but maybe it helps you with implementing a more elegant version. It works by invoking a routine on creation of the chat component, with both partners sending a status with the current time each two seconds. When there is no partner status found yet, the function infers that the partner has not entered yet. When the partner's last status timestamp is older than some timeout range of seconds, then it concludes that the partner has left the chat (irrespective of her/him clicking the [next] button or closing the browser window). 

Sorry for annoying again 😅 
But I think this would make the Chat component even better.

**Edit**:
I will also work on adding the time variable to messages in my experiment if you want to look into it. But you probably won't need to as I think adding this addition would be rather trivial...

**Comment by marcelklehr** [comment]
Thanks for the detailed feedback! These are very good points!

I've created two new syncable properties for the Chat component:

* `data`: contains the same data as `messages`, but in tabular for (`{chatMessage: [], chatParticipantId: [], chatTime: []}`)
* `participants`: contains a list of participant IDs that are currently viewing the chat in the same room (so you can count them or do other things )

$magpie.socket also has a new reactive `participants` property which contains IDs of all participants that are online in the same experiment room (not necessarily viewing the chat, though).

These changes are published in v0.3.2

Let me know what you think :wave

**Comment by marcelklehr** [comment]
I'm closing this for now. Feel free to shout, if you have issues or questions! :)
