### ISSUE TITLE
Add webgazer

### ISSUE THREAD

**Issue by marcelklehr** [magpie-ea/magpie-base#36]
https://github.com/brownhci/WebGazer/

**Comment by marcelklehr** [comment]
Based on the response, I'm unsure, whether we are eligible to license the project under LGPL :thinking: https://github.com/brownhci/WebGazer/issues/224#issuecomment-861705281

**Comment by x-ji** [comment]
From my reading of the reply, I’m not sure if anybody will take up an issue with _magpie if we follow the terms of LGPL :) Maybe we could worry about it if _magpie really takes off and becomes hugely popular 😄

**Comment by x-ji** [comment]
> the LGPL extends to institutions beyond companies, so non-profits or academic institutes or LLCs under $1M, etc.

Seems to me from this sentence that the 1M cap is only applicable to LLC. Also academic Institutes don’t have such a “valuation” attached to them anyways.

**Comment by x-ji** [comment]
Though it’s a good question to clarify, sure 👍 . I think the responder seems to have given a go-ahead?

**Comment by marcelklehr** [comment]
> academic Institutes don’t have such a “valuation” attached to them anyways.

Yeah, it's a bit weird. Either be open source or don't...

**Comment by marcelklehr** [comment]
Eyetracking can be tested at https://magpie-reference.netlify.app/#eyetrackingvalidationscreen
